apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-1
  region: us-east-1

managednodeGroups:
  - name: spot-1
    instanceType: t3.medium
    desiredCapacity: 1
    spot: true
    ssh:
      publicKeyName: Demo_key