apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managednodeGroups:
  - name: expense
    instanceType: t3.medium
    desiredCapacity: 3
    spot: true
    ssh:
      publicKeyName: Demo_key