apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: project-1
  region: us-east-1

managednodeGroups:
  - name: project-1
    instanceDistribution:
      instanceType: t3.medium
    desiredCapacity: 3
    spot: true
    ssh:
      publicKeyName: Demo_key